[package]
name = "mqtt-example"
version = "0.1.0"
edition = "2021"

[dependencies]
bytes = "1.4.0"
json = "0.12.4"
rocket = "0.4.11"
rumqttc = "0.21.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
